### ISSUE TITLE
Page Loading Takes Time

### ISSUE THREAD

**Issue by pranitbauva1997** [xypnox/posters#1]
Hey, nice repo!

I visited https://posters.xypnox.com and it took about 30s to load. Checking out the source code, it seems that you have many images of size around 500kb to 1mb and about 20 posters so that would obviously take a lot of time. Plus the resolution of each image is quite big.

One suggestion: Make another set of images and decrease the resolution to 1/3 of current height and 1/3 of their current width. This would reduce the total size of the image to 1/9 which can reduce the time to load to a few seconds. And when the user clicks on the image, load the full resolution image.

**Comment by xypnox** [comment]
Hi,

Thanks for the feedback. This is an issue that I am also currently
considering.

Apart from the proposed solution, there are a few other things that I would
like to implement. One is dynamic loading of images. So not all images have
to load for the site to be usable. Apart from that, I want the process of
adding a new poster as effortless as possible. Currently, I only need to
copy a poster image of any type, jpeg, png, svg to the images folder and
run the genData.js script and everything updates.

The compression can be implemented in the genData step. Also, I would love
to combine the genData script with the default react build so that the data
is generated by automatically watching the folder at build time.

**Comment by xypnox** [comment]
Hey,

I have completed the compression and resizing step completely.

 This is in the commit: https://github.com/xypnox/posters/commit/1e7f57767b3c15f8d1bd3acbd5205f10531ac92c

Now the page is only ~1.5 MB and loads in 3 seconds for all images. Clicking on the grid images still open uncompressed images.

**Comment by pranitbauva1997** [comment]
Awesome! :+1:
